---
application:
  name: "rcrd-api"
  project: "RCRD API"
  organization: "QoveryCommunity"
  port: 3000
routers:
- name: "main-rcrd-api"
  custom_domains:
  - branch: main
    domain: api.rcrd.me
  routes:
  - application_name: "rcrd-api"
    paths:
    - "/*"
